services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME-records}
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD-awesomeness}
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./scripts/postgres-init-files/01-create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql"
    ports:
      - "${DB_PORT-5432}:5432"

volumes:
  postgres:
