services:
  server:
    build: .
    env_file: .env
    environment:
      - "DEBUG=${DEBUG-true}"
      - "HOST=${HOST-0.0.0.0}"
      - "PORT=${PORT-8000}"
      - "DB_NAME=${DB_NAME-records}"
      - "DB_USER=${DB_USER-postgres}"
      - "DB_PASSWORD=${DB_PASSWORD-awesomeness}"
      - "DB_PORT=${DB_PORT-5432}"
    ports:
      - "${PORT-8000}:${PORT-8000}"
    volumes:
      - "./records:/app/records"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME-records}
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD-awesomeness}
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./scripts:/root/scripts"
    ports:
      - "${DB_PORT-5432}:${DB_PORT-5432}"

volumes:
  postgres:
