services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME-records}
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD-awesomeness}
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./sql/:/docker-entrypoint-initdb.d/"
    ports:
      - "${DB_PORT-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "su", "-", "Postgres", "&&", "/usr/bin/pg_isready"]
      interval: 2s
      timeout: 10s
      retries: 5

volumes:
  postgres:
