version: "3.1"

services:
  server:
    build: .
    env_file: .env
    ports:
      - "${PORT}:8000"
    volumes:
      - "./records:/app/records"
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./scripts:/root/scripts"
